
f21: &devenv
  build: devenv/f21
  privileged: true
  user: 1000
  volumes:
    - &code  ../../:/code
    - &projectdir ../../../:/project

f20:
  <<: *devenv
  build: devenv/f20


centos7:
  <<: *devenv
  build: devenv/centos7

ci:
    build: ci/f20

